services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3


  airflow-init:
    image: apache/airflow:2.9.0
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username ${AIRFLOW_USERNAME} \
          --password ${AIRFLOW_PASSWORD} \
          --firstname ${AIRFLOW_FIRSTNAME} \
          --lastname ${AIRFLOW_LASTNAME} \
          --role Admin \
          --email ${AIRFLOW_EMAIL}

  airflow:
    image: apache/airflow:2.9.0
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: bash -c "airflow webserver & airflow scheduler"

volumes:
  postgres_data:
